// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class GEMKitFFigen {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GEMKitFFigen(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GEMKitFFigen.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> native_call_marker_add(
    ffi.Pointer<ffi.Char> json,
    int jsonSize,
    int markerId,
  ) {
    return _native_call_marker_add(
      json,
      jsonSize,
      markerId,
    );
  }

  late final _native_call_marker_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Long,
              ffi.Long)>>('native_call_marker_add');
  late final _native_call_marker_add = _native_call_marker_addPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, int, int)>();

  ffi.Pointer<ffi.Char> native_call_createObject(
    ffi.Pointer<ffi.Char> json,
    int jsonSize,
  ) {
    return _native_call_createObject(
      json,
      jsonSize,
    );
  }

  late final _native_call_createObjectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>, ffi.Long)>>('native_call_createObject');
  late final _native_call_createObject = _native_call_createObjectPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, int)>();

  void native_register_callback(
    Dart_onNotifyEvent pFunc,
  ) {
    return _native_register_callback(
      pFunc,
    );
  }

  late final _native_register_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(Dart_onNotifyEvent)>>(
          'native_register_callback');
  late final _native_register_callback = _native_register_callbackPtr
      .asFunction<void Function(Dart_onNotifyEvent)>();

  void native_deleteObject(
    ffi.Pointer<ffi.Char> json,
    int theSize,
  ) {
    return _native_deleteObject(
      json,
      theSize,
    );
  }

  late final _native_deleteObjectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>, ffi.Long)>>('native_deleteObject');
  late final _native_deleteObject = _native_deleteObjectPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();
}

typedef Dart_onNotifyEvent
    = ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>;
